baseurl: "/"
languageCode: "en-us"
defaultContentLanguage: "en"
# defaultContentLanguage: "zh"
title: "ðŸ…¿ðŸ†‚ðŸ†ˆðŸ…ºðŸ…¸ðŸ†ƒ-ðŸ…»ðŸ…´ðŸ…°ðŸ†ðŸ…½"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: "https-jwlearn-netlify-app"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"
paginate: 2

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: Search
      url: "#"
      identifier: menu-search
#    - name: Subscribe
#      url: "index.xml"
  footer:
    - name: Contact
      url: "card/contact"
      weight: 1
    - name: Categories
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 3
      pre: "optional"
#    - name: Suggest an edit
#      url: "#"
#      weight: 4
#      identifier: "menu-edit"
    - name: Back to top
      url: "#"

params:
  homePosts: 10
  likerID: "tsai_jiewen"
  mainSections: [""]
  editLink: "/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo and blogdown with the hugo-prose theme.
  footer: >
    &copy; [JW Tsai](/) 2020 - 2021
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source is available at
    https://github.com/tsai-jiewen/psykit-learn.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
